services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - ['setContainer', ['@Psr\Container\ContainerInterface']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    Janborg\ContaoIcal\Cron\GenerateIcalCron:
        arguments:
            - '@contao.framework'

    Janborg\ContaoIcal\Cron\RemoveOldIcalFilesCron:
        arguments:
            - '@contao.framework'

    Janborg\ContaoIcal\Controller\IcalCalendarController: 
        tags: 
            - 'controller.service_arguments'
                